# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import car_assistant_pb2 as car__assistant__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in car_assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CarAssistantStub:
    """============================================================
    核心服务
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/car_assistant.CarAssistant/GetHealth',
                request_serializer=car__assistant__pb2.Empty.SerializeToString,
                response_deserializer=car__assistant__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ChatQuery = channel.unary_unary(
                '/car_assistant.CarAssistant/ChatQuery',
                request_serializer=car__assistant__pb2.ChatRequest.SerializeToString,
                response_deserializer=car__assistant__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.StreamChat = channel.unary_stream(
                '/car_assistant.CarAssistant/StreamChat',
                request_serializer=car__assistant__pb2.ChatRequest.SerializeToString,
                response_deserializer=car__assistant__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/car_assistant.CarAssistant/ExecuteTool',
                request_serializer=car__assistant__pb2.ToolRequest.SerializeToString,
                response_deserializer=car__assistant__pb2.ToolResponse.FromString,
                _registered_method=True)


class CarAssistantServicer:
    """============================================================
    核心服务
    ============================================================
    """

    def GetHealth(self, request, context):
        """健康检查（等价 GET /api/health）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatQuery(self, request, context):
        """单次对话（等价 POST /api/chat）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChat(self, request, context):
        """流式对话（等价 POST /api/chat/stream，SSE → gRPC Server-Sent Streaming）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """执行工具（等价 POST /api/command）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarAssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=car__assistant__pb2.Empty.FromString,
                    response_serializer=car__assistant__pb2.HealthResponse.SerializeToString,
            ),
            'ChatQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatQuery,
                    request_deserializer=car__assistant__pb2.ChatRequest.FromString,
                    response_serializer=car__assistant__pb2.ChatResponse.SerializeToString,
            ),
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=car__assistant__pb2.ChatRequest.FromString,
                    response_serializer=car__assistant__pb2.ChatResponse.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=car__assistant__pb2.ToolRequest.FromString,
                    response_serializer=car__assistant__pb2.ToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'car_assistant.CarAssistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('car_assistant.CarAssistant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarAssistant:
    """============================================================
    核心服务
    ============================================================
    """

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/car_assistant.CarAssistant/GetHealth',
            car__assistant__pb2.Empty.SerializeToString,
            car__assistant__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/car_assistant.CarAssistant/ChatQuery',
            car__assistant__pb2.ChatRequest.SerializeToString,
            car__assistant__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/car_assistant.CarAssistant/StreamChat',
            car__assistant__pb2.ChatRequest.SerializeToString,
            car__assistant__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/car_assistant.CarAssistant/ExecuteTool',
            car__assistant__pb2.ToolRequest.SerializeToString,
            car__assistant__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
