// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: car_assistant.proto

#include "car_assistant.pb.h"
#include "car_assistant.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace car_assistant {

static const char* CarAssistant_method_names[] = {
  "/car_assistant.CarAssistant/GetHealth",
  "/car_assistant.CarAssistant/ChatQuery",
  "/car_assistant.CarAssistant/StreamChat",
  "/car_assistant.CarAssistant/ExecuteTool",
};

std::unique_ptr< CarAssistant::Stub> CarAssistant::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CarAssistant::Stub> stub(new CarAssistant::Stub(channel, options));
  return stub;
}

CarAssistant::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetHealth_(CarAssistant_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ChatQuery_(CarAssistant_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamChat_(CarAssistant_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ExecuteTool_(CarAssistant_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CarAssistant::Stub::GetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::car_assistant::HealthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::car_assistant::Empty, ::car_assistant::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetHealth_, context, request, response);
}

void CarAssistant::Stub::async::GetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty* request, ::car_assistant::HealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::car_assistant::Empty, ::car_assistant::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHealth_, context, request, response, std::move(f));
}

void CarAssistant::Stub::async::GetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty* request, ::car_assistant::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHealth_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::car_assistant::HealthResponse>* CarAssistant::Stub::PrepareAsyncGetHealthRaw(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::car_assistant::HealthResponse, ::car_assistant::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetHealth_, context, request);
}

::grpc::ClientAsyncResponseReader< ::car_assistant::HealthResponse>* CarAssistant::Stub::AsyncGetHealthRaw(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetHealthRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CarAssistant::Stub::ChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::car_assistant::ChatResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::car_assistant::ChatRequest, ::car_assistant::ChatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ChatQuery_, context, request, response);
}

void CarAssistant::Stub::async::ChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest* request, ::car_assistant::ChatResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::car_assistant::ChatRequest, ::car_assistant::ChatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ChatQuery_, context, request, response, std::move(f));
}

void CarAssistant::Stub::async::ChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest* request, ::car_assistant::ChatResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ChatQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::car_assistant::ChatResponse>* CarAssistant::Stub::PrepareAsyncChatQueryRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::car_assistant::ChatResponse, ::car_assistant::ChatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ChatQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::car_assistant::ChatResponse>* CarAssistant::Stub::AsyncChatQueryRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncChatQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::car_assistant::ChatResponse>* CarAssistant::Stub::StreamChatRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::car_assistant::ChatResponse>::Create(channel_.get(), rpcmethod_StreamChat_, context, request);
}

void CarAssistant::Stub::async::StreamChat(::grpc::ClientContext* context, const ::car_assistant::ChatRequest* request, ::grpc::ClientReadReactor< ::car_assistant::ChatResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::car_assistant::ChatResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamChat_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::car_assistant::ChatResponse>* CarAssistant::Stub::AsyncStreamChatRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::car_assistant::ChatResponse>::Create(channel_.get(), cq, rpcmethod_StreamChat_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::car_assistant::ChatResponse>* CarAssistant::Stub::PrepareAsyncStreamChatRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::car_assistant::ChatResponse>::Create(channel_.get(), cq, rpcmethod_StreamChat_, context, request, false, nullptr);
}

::grpc::Status CarAssistant::Stub::ExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::car_assistant::ToolResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::car_assistant::ToolRequest, ::car_assistant::ToolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteTool_, context, request, response);
}

void CarAssistant::Stub::async::ExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest* request, ::car_assistant::ToolResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::car_assistant::ToolRequest, ::car_assistant::ToolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteTool_, context, request, response, std::move(f));
}

void CarAssistant::Stub::async::ExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest* request, ::car_assistant::ToolResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteTool_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::car_assistant::ToolResponse>* CarAssistant::Stub::PrepareAsyncExecuteToolRaw(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::car_assistant::ToolResponse, ::car_assistant::ToolRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteTool_, context, request);
}

::grpc::ClientAsyncResponseReader< ::car_assistant::ToolResponse>* CarAssistant::Stub::AsyncExecuteToolRaw(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteToolRaw(context, request, cq);
  result->StartCall();
  return result;
}

CarAssistant::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CarAssistant_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CarAssistant::Service, ::car_assistant::Empty, ::car_assistant::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CarAssistant::Service* service,
             ::grpc::ServerContext* ctx,
             const ::car_assistant::Empty* req,
             ::car_assistant::HealthResponse* resp) {
               return service->GetHealth(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CarAssistant_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CarAssistant::Service, ::car_assistant::ChatRequest, ::car_assistant::ChatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CarAssistant::Service* service,
             ::grpc::ServerContext* ctx,
             const ::car_assistant::ChatRequest* req,
             ::car_assistant::ChatResponse* resp) {
               return service->ChatQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CarAssistant_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< CarAssistant::Service, ::car_assistant::ChatRequest, ::car_assistant::ChatResponse>(
          [](CarAssistant::Service* service,
             ::grpc::ServerContext* ctx,
             const ::car_assistant::ChatRequest* req,
             ::grpc::ServerWriter<::car_assistant::ChatResponse>* writer) {
               return service->StreamChat(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CarAssistant_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CarAssistant::Service, ::car_assistant::ToolRequest, ::car_assistant::ToolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CarAssistant::Service* service,
             ::grpc::ServerContext* ctx,
             const ::car_assistant::ToolRequest* req,
             ::car_assistant::ToolResponse* resp) {
               return service->ExecuteTool(ctx, req, resp);
             }, this)));
}

CarAssistant::Service::~Service() {
}

::grpc::Status CarAssistant::Service::GetHealth(::grpc::ServerContext* context, const ::car_assistant::Empty* request, ::car_assistant::HealthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CarAssistant::Service::ChatQuery(::grpc::ServerContext* context, const ::car_assistant::ChatRequest* request, ::car_assistant::ChatResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CarAssistant::Service::StreamChat(::grpc::ServerContext* context, const ::car_assistant::ChatRequest* request, ::grpc::ServerWriter< ::car_assistant::ChatResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CarAssistant::Service::ExecuteTool(::grpc::ServerContext* context, const ::car_assistant::ToolRequest* request, ::car_assistant::ToolResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace car_assistant

