// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: car_assistant.proto
// Original file comments:
// gRPC proto 定义 — 车载娱乐系统 HMI ↔ Agent 通信
// 升级自 HTTP/JSON 协议，保持接口等价
#ifndef GRPC_car_5fassistant_2eproto__INCLUDED
#define GRPC_car_5fassistant_2eproto__INCLUDED

#include "car_assistant.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace car_assistant {

// ============================================================
// 核心服务
// ============================================================
class CarAssistant final {
 public:
  static constexpr char const* service_full_name() {
    return "car_assistant.CarAssistant";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 健康检查（等价 GET /api/health）
    virtual ::grpc::Status GetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::car_assistant::HealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::HealthResponse>> AsyncGetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::HealthResponse>>(AsyncGetHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::HealthResponse>> PrepareAsyncGetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::HealthResponse>>(PrepareAsyncGetHealthRaw(context, request, cq));
    }
    // 单次对话（等价 POST /api/chat）
    virtual ::grpc::Status ChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::car_assistant::ChatResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ChatResponse>> AsyncChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ChatResponse>>(AsyncChatQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ChatResponse>> PrepareAsyncChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ChatResponse>>(PrepareAsyncChatQueryRaw(context, request, cq));
    }
    // 流式对话（等价 POST /api/chat/stream，SSE → gRPC Server-Sent Streaming）
    std::unique_ptr< ::grpc::ClientReaderInterface< ::car_assistant::ChatResponse>> StreamChat(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::car_assistant::ChatResponse>>(StreamChatRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::car_assistant::ChatResponse>> AsyncStreamChat(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::car_assistant::ChatResponse>>(AsyncStreamChatRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::car_assistant::ChatResponse>> PrepareAsyncStreamChat(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::car_assistant::ChatResponse>>(PrepareAsyncStreamChatRaw(context, request, cq));
    }
    // 执行工具（等价 POST /api/command）
    virtual ::grpc::Status ExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::car_assistant::ToolResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ToolResponse>> AsyncExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ToolResponse>>(AsyncExecuteToolRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ToolResponse>> PrepareAsyncExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ToolResponse>>(PrepareAsyncExecuteToolRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 健康检查（等价 GET /api/health）
      virtual void GetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty* request, ::car_assistant::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty* request, ::car_assistant::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 单次对话（等价 POST /api/chat）
      virtual void ChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest* request, ::car_assistant::ChatResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest* request, ::car_assistant::ChatResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 流式对话（等价 POST /api/chat/stream，SSE → gRPC Server-Sent Streaming）
      virtual void StreamChat(::grpc::ClientContext* context, const ::car_assistant::ChatRequest* request, ::grpc::ClientReadReactor< ::car_assistant::ChatResponse>* reactor) = 0;
      // 执行工具（等价 POST /api/command）
      virtual void ExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest* request, ::car_assistant::ToolResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest* request, ::car_assistant::ToolResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::HealthResponse>* AsyncGetHealthRaw(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::HealthResponse>* PrepareAsyncGetHealthRaw(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ChatResponse>* AsyncChatQueryRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ChatResponse>* PrepareAsyncChatQueryRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::car_assistant::ChatResponse>* StreamChatRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::car_assistant::ChatResponse>* AsyncStreamChatRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::car_assistant::ChatResponse>* PrepareAsyncStreamChatRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ToolResponse>* AsyncExecuteToolRaw(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::car_assistant::ToolResponse>* PrepareAsyncExecuteToolRaw(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::car_assistant::HealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::HealthResponse>> AsyncGetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::HealthResponse>>(AsyncGetHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::HealthResponse>> PrepareAsyncGetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::HealthResponse>>(PrepareAsyncGetHealthRaw(context, request, cq));
    }
    ::grpc::Status ChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::car_assistant::ChatResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::ChatResponse>> AsyncChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::ChatResponse>>(AsyncChatQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::ChatResponse>> PrepareAsyncChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::ChatResponse>>(PrepareAsyncChatQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::car_assistant::ChatResponse>> StreamChat(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::car_assistant::ChatResponse>>(StreamChatRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::car_assistant::ChatResponse>> AsyncStreamChat(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::car_assistant::ChatResponse>>(AsyncStreamChatRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::car_assistant::ChatResponse>> PrepareAsyncStreamChat(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::car_assistant::ChatResponse>>(PrepareAsyncStreamChatRaw(context, request, cq));
    }
    ::grpc::Status ExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::car_assistant::ToolResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::ToolResponse>> AsyncExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::ToolResponse>>(AsyncExecuteToolRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::ToolResponse>> PrepareAsyncExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::car_assistant::ToolResponse>>(PrepareAsyncExecuteToolRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty* request, ::car_assistant::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      void GetHealth(::grpc::ClientContext* context, const ::car_assistant::Empty* request, ::car_assistant::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest* request, ::car_assistant::ChatResponse* response, std::function<void(::grpc::Status)>) override;
      void ChatQuery(::grpc::ClientContext* context, const ::car_assistant::ChatRequest* request, ::car_assistant::ChatResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamChat(::grpc::ClientContext* context, const ::car_assistant::ChatRequest* request, ::grpc::ClientReadReactor< ::car_assistant::ChatResponse>* reactor) override;
      void ExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest* request, ::car_assistant::ToolResponse* response, std::function<void(::grpc::Status)>) override;
      void ExecuteTool(::grpc::ClientContext* context, const ::car_assistant::ToolRequest* request, ::car_assistant::ToolResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::car_assistant::HealthResponse>* AsyncGetHealthRaw(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::car_assistant::HealthResponse>* PrepareAsyncGetHealthRaw(::grpc::ClientContext* context, const ::car_assistant::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::car_assistant::ChatResponse>* AsyncChatQueryRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::car_assistant::ChatResponse>* PrepareAsyncChatQueryRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::car_assistant::ChatResponse>* StreamChatRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request) override;
    ::grpc::ClientAsyncReader< ::car_assistant::ChatResponse>* AsyncStreamChatRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::car_assistant::ChatResponse>* PrepareAsyncStreamChatRaw(::grpc::ClientContext* context, const ::car_assistant::ChatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::car_assistant::ToolResponse>* AsyncExecuteToolRaw(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::car_assistant::ToolResponse>* PrepareAsyncExecuteToolRaw(::grpc::ClientContext* context, const ::car_assistant::ToolRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetHealth_;
    const ::grpc::internal::RpcMethod rpcmethod_ChatQuery_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamChat_;
    const ::grpc::internal::RpcMethod rpcmethod_ExecuteTool_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 健康检查（等价 GET /api/health）
    virtual ::grpc::Status GetHealth(::grpc::ServerContext* context, const ::car_assistant::Empty* request, ::car_assistant::HealthResponse* response);
    // 单次对话（等价 POST /api/chat）
    virtual ::grpc::Status ChatQuery(::grpc::ServerContext* context, const ::car_assistant::ChatRequest* request, ::car_assistant::ChatResponse* response);
    // 流式对话（等价 POST /api/chat/stream，SSE → gRPC Server-Sent Streaming）
    virtual ::grpc::Status StreamChat(::grpc::ServerContext* context, const ::car_assistant::ChatRequest* request, ::grpc::ServerWriter< ::car_assistant::ChatResponse>* writer);
    // 执行工具（等价 POST /api/command）
    virtual ::grpc::Status ExecuteTool(::grpc::ServerContext* context, const ::car_assistant::ToolRequest* request, ::car_assistant::ToolResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetHealth() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::car_assistant::Empty* /*request*/, ::car_assistant::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetHealth(::grpc::ServerContext* context, ::car_assistant::Empty* request, ::grpc::ServerAsyncResponseWriter< ::car_assistant::HealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ChatQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ChatQuery() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ChatQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatQuery(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::car_assistant::ChatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestChatQuery(::grpc::ServerContext* context, ::car_assistant::ChatRequest* request, ::grpc::ServerAsyncResponseWriter< ::car_assistant::ChatResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamChat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamChat() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_StreamChat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChat(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::grpc::ServerWriter< ::car_assistant::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamChat(::grpc::ServerContext* context, ::car_assistant::ChatRequest* request, ::grpc::ServerAsyncWriter< ::car_assistant::ChatResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ExecuteTool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExecuteTool() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ExecuteTool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTool(::grpc::ServerContext* /*context*/, const ::car_assistant::ToolRequest* /*request*/, ::car_assistant::ToolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteTool(::grpc::ServerContext* context, ::car_assistant::ToolRequest* request, ::grpc::ServerAsyncResponseWriter< ::car_assistant::ToolResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetHealth<WithAsyncMethod_ChatQuery<WithAsyncMethod_StreamChat<WithAsyncMethod_ExecuteTool<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetHealth() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::car_assistant::Empty, ::car_assistant::HealthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::car_assistant::Empty* request, ::car_assistant::HealthResponse* response) { return this->GetHealth(context, request, response); }));}
    void SetMessageAllocatorFor_GetHealth(
        ::grpc::MessageAllocator< ::car_assistant::Empty, ::car_assistant::HealthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::car_assistant::Empty, ::car_assistant::HealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::car_assistant::Empty* /*request*/, ::car_assistant::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetHealth(
      ::grpc::CallbackServerContext* /*context*/, const ::car_assistant::Empty* /*request*/, ::car_assistant::HealthResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ChatQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ChatQuery() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::car_assistant::ChatRequest, ::car_assistant::ChatResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::car_assistant::ChatRequest* request, ::car_assistant::ChatResponse* response) { return this->ChatQuery(context, request, response); }));}
    void SetMessageAllocatorFor_ChatQuery(
        ::grpc::MessageAllocator< ::car_assistant::ChatRequest, ::car_assistant::ChatResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::car_assistant::ChatRequest, ::car_assistant::ChatResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ChatQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatQuery(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::car_assistant::ChatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ChatQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::car_assistant::ChatResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamChat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamChat() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::car_assistant::ChatRequest, ::car_assistant::ChatResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::car_assistant::ChatRequest* request) { return this->StreamChat(context, request); }));
    }
    ~WithCallbackMethod_StreamChat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChat(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::grpc::ServerWriter< ::car_assistant::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::car_assistant::ChatResponse>* StreamChat(
      ::grpc::CallbackServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ExecuteTool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExecuteTool() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::car_assistant::ToolRequest, ::car_assistant::ToolResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::car_assistant::ToolRequest* request, ::car_assistant::ToolResponse* response) { return this->ExecuteTool(context, request, response); }));}
    void SetMessageAllocatorFor_ExecuteTool(
        ::grpc::MessageAllocator< ::car_assistant::ToolRequest, ::car_assistant::ToolResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::car_assistant::ToolRequest, ::car_assistant::ToolResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ExecuteTool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTool(::grpc::ServerContext* /*context*/, const ::car_assistant::ToolRequest* /*request*/, ::car_assistant::ToolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteTool(
      ::grpc::CallbackServerContext* /*context*/, const ::car_assistant::ToolRequest* /*request*/, ::car_assistant::ToolResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetHealth<WithCallbackMethod_ChatQuery<WithCallbackMethod_StreamChat<WithCallbackMethod_ExecuteTool<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetHealth() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::car_assistant::Empty* /*request*/, ::car_assistant::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ChatQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ChatQuery() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ChatQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatQuery(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::car_assistant::ChatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamChat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamChat() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_StreamChat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChat(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::grpc::ServerWriter< ::car_assistant::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ExecuteTool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExecuteTool() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ExecuteTool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTool(::grpc::ServerContext* /*context*/, const ::car_assistant::ToolRequest* /*request*/, ::car_assistant::ToolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetHealth() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::car_assistant::Empty* /*request*/, ::car_assistant::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ChatQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ChatQuery() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ChatQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatQuery(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::car_assistant::ChatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestChatQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamChat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamChat() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_StreamChat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChat(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::grpc::ServerWriter< ::car_assistant::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamChat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExecuteTool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExecuteTool() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ExecuteTool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTool(::grpc::ServerContext* /*context*/, const ::car_assistant::ToolRequest* /*request*/, ::car_assistant::ToolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteTool(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetHealth() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetHealth(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::car_assistant::Empty* /*request*/, ::car_assistant::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetHealth(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ChatQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ChatQuery() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ChatQuery(context, request, response); }));
    }
    ~WithRawCallbackMethod_ChatQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatQuery(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::car_assistant::ChatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ChatQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamChat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamChat() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamChat(context, request); }));
    }
    ~WithRawCallbackMethod_StreamChat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChat(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::grpc::ServerWriter< ::car_assistant::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamChat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExecuteTool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExecuteTool() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExecuteTool(context, request, response); }));
    }
    ~WithRawCallbackMethod_ExecuteTool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTool(::grpc::ServerContext* /*context*/, const ::car_assistant::ToolRequest* /*request*/, ::car_assistant::ToolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteTool(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetHealth() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::car_assistant::Empty, ::car_assistant::HealthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::car_assistant::Empty, ::car_assistant::HealthResponse>* streamer) {
                       return this->StreamedGetHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::car_assistant::Empty* /*request*/, ::car_assistant::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::car_assistant::Empty,::car_assistant::HealthResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ChatQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ChatQuery() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::car_assistant::ChatRequest, ::car_assistant::ChatResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::car_assistant::ChatRequest, ::car_assistant::ChatResponse>* streamer) {
                       return this->StreamedChatQuery(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ChatQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ChatQuery(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::car_assistant::ChatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedChatQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::car_assistant::ChatRequest,::car_assistant::ChatResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExecuteTool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExecuteTool() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::car_assistant::ToolRequest, ::car_assistant::ToolResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::car_assistant::ToolRequest, ::car_assistant::ToolResponse>* streamer) {
                       return this->StreamedExecuteTool(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExecuteTool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExecuteTool(::grpc::ServerContext* /*context*/, const ::car_assistant::ToolRequest* /*request*/, ::car_assistant::ToolResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecuteTool(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::car_assistant::ToolRequest,::car_assistant::ToolResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetHealth<WithStreamedUnaryMethod_ChatQuery<WithStreamedUnaryMethod_ExecuteTool<Service > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamChat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamChat() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::car_assistant::ChatRequest, ::car_assistant::ChatResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::car_assistant::ChatRequest, ::car_assistant::ChatResponse>* streamer) {
                       return this->StreamedStreamChat(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamChat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamChat(::grpc::ServerContext* /*context*/, const ::car_assistant::ChatRequest* /*request*/, ::grpc::ServerWriter< ::car_assistant::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamChat(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::car_assistant::ChatRequest,::car_assistant::ChatResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamChat<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetHealth<WithStreamedUnaryMethod_ChatQuery<WithSplitStreamingMethod_StreamChat<WithStreamedUnaryMethod_ExecuteTool<Service > > > > StreamedService;
};

}  // namespace car_assistant


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_car_5fassistant_2eproto__INCLUDED
